title: Winston Spencer
email: winston.spencer@ndsu.edu
description: Developer focused on ML, distributed systems, and cloud solutions.
url: "https://winston-spencer.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social links
github_username: winston-spencer
linkedin_username: winston-spencer

# Exclude from processing
exclude:
  - Gemfile
  - README.md
  - Gemfile.lock
  - Gemfile.lock
  - README.md
# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
